version: '3.8'

services:

  mysql-container:
    image: mysql:latest
    volumes:
      - mysql1:/var/lib/mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: test123
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    expose:
      - "3308"

  mysql-container1:
    image: mysql:latest
    volumes:
      - mysql1:/var/lib/mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: test123
      MYSQL_TCP_PORT: 3307
    ports:
    - "3307:3307"
    expose:
    - "3307"

  mysql-container2:
    image: mysql:latest
    volumes:
      - mysql2:/var/lib/mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: test123
      MYSQL_TCP_PORT: 3309
    ports:
      - "3309:3309"
    expose:
      - "3309"

  cinema-eureka-server:
    image: marcinlupa1987/cinema-repo:cinema-eureka-server
    build:
      context: ./cinema-eureka-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8761:8761"

  cinema-users-service:
    image: marcinlupa1987/cinema-repo:cinema-users-service
    build:
      context: ./cinema-users-service
      dockerfile: Dockerfile
    restart: always
    ports:
    - "8100"

  cinema-ticket-service:
    image: marcinlupa1987/cinema-repo:cinema-ticket-service
    build:
      context: ./cinema-ticket-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8100"
  cinema-seance-service:
    image: marcinlupa1987/cinema-repo:cinema-seance-service
    build:
      context: ./cinema-seance-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8102"

  cinema-api-gateway:
    image: marcinlupa1987/cinema-repo:cinema-api-gateway
    build:
      context: ./cinema-api-gateway
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"

  cinema-spring-cloud-server:
    image: marcinlupa1987/cinema-repo:cinema-spring-cloud-server
    build:
      context: ./cinema-spring-cloud-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8888:8888"

volumes:
  mysql1:
  mysql2:
  mysql3: